name: CoreWallet API CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Forçar Instalação do Motor do Prisma
        run: npm install @prisma/client
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Run tests Automatically
        run: npx jest
    env:
        JWT_SECRET: "chave_secreta_falsa_para_testes"
